__author__ = 'Jonathan'

LONG_TIME_WINDOW = 300
SHORT_TIME_WINDOW = 5
ENTROPY_RADIUS = 5

DFA_WINDOW_LEN = 10 # no. of lines

CONTROL = ['APPLE', 'DAFODIL', 'LILLY', 'LILY', 'ORANGE', 'ROSE', 'SUNFLOWER', 'SWEETPEA']
SICK_PATIENTS = ['CHERRY', 'CROCUS', 'DAISY', 'DAISEY', 'FLOX', 'IRIS', 'MAPLE', 'ORCHID', 'PEONY', 'VIOLET']
PATIENTS = SICK_PATIENTS+CONTROL
UNDERLINES_BEFORE_NAME = 2
DATA_LEN = 1000000000

DATA_TABLE_FILE_PATH = 'C:\ML\parkinson\FIRSTDATA\DATAFile.csv'
SHORT_TABLE_FILE_PATH = 'C:\ML\parkinson\FIRSTDATA\SHORTFile.csv'
LONG_TABLE_FILE_PATH = 'C:\ML\parkinson\FIRSTDATA\LONGFile.csv'
ENTIRE_TABLE_FILE_PATH = 'C:\ML\parkinson\FIRSTDATA\ENTIREFile.csv'
NUM_COEFFS = 5

FREQ_H = 5
FREQ_L = 10


delete = False


import logging
LOG_LEVEL = 'DEBUG'
numeric_level = getattr(logging, LOG_LEVEL, None)
logging.basicConfig(level=numeric_level)



